name: Build

on:
  repository_dispatch:
    types: [stdlib-publish-snapshot]
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate CodeCov Report
        uses: codecov/codecov-action@v1
